manikshop/urls.py
from django.urls import path, re_path
from . import views

# from django.conf.urls import url
from . import views
app_name = 'manikshop'

urlpatterns = [
    re_path(r'^getSubcategory/$', views.get_subcategory),
    path('',views.index, name="index" ),
    path('product/',views.product, name="product" ),
    path('deal-product/<int:id>',views.deal_product, name="deal-product" ),
    path('search/<str:search_type>/<int:id>',views.search, name="search" ),
    path('default_search',views.default_search, name="default_search"),
    path('single/<int:id>',views.single, name="single"),
    path('about',views.about, name="about" ),
    path('contact',views.contact, name="contact"),
    path('contact-form',views.contact_form, name="contact-form"),
    path('cart',views.cart, name="cart"),
    path('confirm-order/<str:mode>/<str:id>',views.confirm_order, name="confirm-order"),
    path('order-history',views.order_history, name="order-history"),
    path('faqs',views.faqs, name="faqs"),
    path('checkout/<str:id>',views.checkout, name="checkout"),
    path('terms',views.terms, name="terms"),
    path('payment',views.payment, name="payment"),
    path('privacy',views.privacy, name="privacy"),
    path('signup',views.signup, name="signup"),
    path('login',views.login, name="login"),
    path('logout',views.logout, name="logout"),
    path('profile',views.profile, name="profile"),
    path('update-address',views.update_address, name="update-address"),
    path('add-cart/<int:id>',views.add_cart, name="add-cart"),
    path('remove-cart/<int:id>',views.remove_cart, name="remove-cart"),
    path('create-order',views.create_order, name="create-order"),
    path('track-order',views.track_order, name="track-order"),
    path('subscription',views.subscription, name="subscription"),
    path('generate-report/<str:order_id>',views.generate_report, name="generate-report"),
    #for payment gateway
    path('update-payment-status',views.update_payment_status, name="update-payment-status"),
]

supershopee/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include("manikshop.urls")),
    path('dashboard/', include("admin_dashboard.urls")),
    path('admin/', admin.site.urls),

    ]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manikshop/models.py
from datetime import date, datetime
from email.policy import default
from django.db import models
from django.contrib.auth.models import User

# for rich text
from ckeditor.fields import RichTextField

# for category
class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    def __str__(self):
        return self.name

# for Sub-category
class SubCategory(models.Model):
    # category = models.ForeignKey(Category, on_delete=models.PROTECT)
    category = models.ForeignKey(Category, related_name='subcategories', on_delete=models.CASCADE)
    name = models.CharField(max_length=50, unique=True)
    def __str__(self):
        return self.name
        

# For Product details
class ProductDetails(models.Model):
    name= models.CharField(max_length=100)
    price= models.FloatField()
    mrp= models.FloatField()
    main_img = models.ImageField(upload_to='product_img')
    img1 = models.ImageField(upload_to='product_img')
    img2 = models.ImageField(upload_to='product_img')
    img3 = models.ImageField(upload_to='product_img')
    category = models.ForeignKey(Category, related_name='produits', on_delete=models.CASCADE)
    subcategory = models.ForeignKey(SubCategory, related_name='produits', on_delete=models.CASCADE)
    product_details = RichTextField(blank=True, null=True)
    trending = models.BooleanField(default=False)
    
    def __str__(self):
        return self.name


# For Order Table
class Order(models.Model):
    order_id = models.CharField(max_length=100, default="")
    cutomer_name = models.ForeignKey(User,  related_name='cust_name', on_delete=models.CASCADE)
    date = models.DateTimeField()
    address = models.CharField(max_length= 500)
    mobile_no = models.CharField(max_length = 12)
    product = models.ForeignKey(ProductDetails,  related_name='product', on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    price = models.FloatField(default=1)
    total_cost = models.FloatField(default=1)
    order_state_list = [
        ('pending', 'Pending'),
        ('cancelled', 'Cancelled'),
        ('confirm', 'Confirm'),
        ('on_the_way', 'On the way'),    
        ('delivered', 'Delivered'),    
        ]
    order_status = models.CharField(max_length=50, choices=order_state_list, default="pending")

    payment_state_list = [
        ('pending', 'Pending'),
        ('cancelled', 'Cancelled'),
        ('confirm', 'Confirm') 
        ]
    payment_status = models.CharField(max_length=50, choices=payment_state_list, default="pending")

    payment_method_list = [
        ('cash', 'Cash On Delivery'),
        ('prepaid', 'Pre-Paid'), 
        ]
    payment_method = models.CharField(max_length=100, choices=payment_method_list, default="cash")
    payment_order_id = models.CharField(max_length=500)
    transaction_id = models.CharField(max_length=100)

    # Generate Order Id
    update_order_id = models.BooleanField(default=True)

    def get_order_id(self):
        today = datetime.now()
        date = today.strftime("%d")
        hrs = today.strftime("%H")
        min = today.strftime("%M")
        self.update_order_id=False 
        return f"{date}{today.month}{today.year}{hrs}{min}{self.cutomer_name.id}"

    # Get price
    def get_price(self):
        pro_id = ProductDetails.objects.get(id=self.product.id)
        return pro_id.price

    # Calculate total cost
    def cal_total(self):
        pro_id = ProductDetails.objects.get(id=self.product.id)
        return pro_id.price * self.quantity

    # Get Address
    def get_address(self):
        user = Extended_user.objects.get(user=self.cutomer_name.id)
        return user.address

    # Get Mobile No
    def get_mobile_no(self):
        user = Extended_user.objects.get(user=self.cutomer_name.id)
        return user.mobile_no

    def save(self, *args, **kwargs):
        if self.update_order_id:
            self.order_id = self.get_order_id()
        self.price = self.get_price()
        self.total_cost = self.cal_total()
        self.address = self.get_address()
        self.mobile_no = self.get_mobile_no()
        super(Order, self).save(*args, **kwargs)

    def __str__(self):
        return self.order_id


# for Cart
class Cart(models.Model):
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    products= models.ManyToManyField(to=ProductDetails, related_name="cart", blank=True)

    def __str__(self):
        return self.name.first_name

# for Deals
class Deal(models.Model):
    id = models.AutoField(primary_key=True)
    name= models.CharField(max_length=100)
    banner = models.ImageField(upload_to='deals')
    offer_line= models.CharField(max_length=300)
    products= models.ManyToManyField(to=ProductDetails, related_name="deals", blank=True)
    start_date= models.DateTimeField()
    end_date = models.DateTimeField()

    def __str__(self):
        return self.name

# Extended user
class Extended_user(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mobile_no = models.CharField(max_length=12)
    address = models.CharField(max_length=500)
    USER_TYPE = (('admin', "Admin"), ('employee', "Employee"), ('customer', "Customer"))
    user_type = models.CharField(choices=USER_TYPE, max_length=10, default="customer")

    def __str__(self):
        return self.user.first_name

# Subscription table
class Subscription(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField()
    date = models.DateField()

    def __str__(self):
        return self.name

# Contact Forms
class Contact_form(models.Model):
    name = models.CharField(max_length=300)
    subject= models.CharField(max_length=500)
    mobile_no = models.CharField(max_length=12)
    email = models.CharField(max_length=200)
    message = models.TextField()
    date= models.DateTimeField(default=datetime.now())
    
    def __str__(self):
        return self.name

templates/01-add-product.html
{% extends '01-admin-base.html' %}
{% load static %}
{% block content %}

    <div class="container tm-mt-big tm-mb-big">
      <div class="row">
        <div class="col-xl-9 col-lg-10 col-md-12 col-sm-12 mx-auto">
          <div class="tm-bg-primary-dark tm-block tm-block-h-auto">
            <div class="row">
              <div class="col-12">
                <h2 class="tm-block-title d-inline-block">Add Product</h2>
              </div>
            </div>
            <div class="row tm-edit-product-row">
              <div class="col-xl-6 col-lg-6 col-md-12">
                <form action="" method="post" enctype="multipart/form-data" class="tm-edit-product-form">
                  {% csrf_token %}
                  {{form.media}}
                  <div class="form-group mb-3">
                    <label
                      for="name"
                      >Product Name
                    </label>
                    {{form.name}}
                    
                  </div>
                  
                  <div class="form-group mb-3">
                    <label
                      for="category"
                      >Category</label
                    >
                    <select
                      class="custom-select tm-select-accounts"
                      id="category" name="category"
                    >
                      <option selected>Select category</option>
                      {% for category in categories %}
                      <option value="{{category.id}}">{{category.name}}</option>
                      {% endfor %}
                    </select>
                  </div>
                  <div class="form-group mb-3">
                    <label
                      for="subcategory"
                      >Sub Category</label
                    >
                    <select
                      class="custom-select tm-select-accounts"
                      id="subcategory" name="subcategory"
                    >
                      <option selected>Select sub-category</option>
                      {% for subcategory in subcategories %}
                      <option value="{{subcategory.id}}">{{subcategory.name}}</option>
                      {% endfor %}
                    </select>
                  </div>
                  <div class="row">
                      <div class="form-group mb-3 col-xs-12 col-sm-6">
                          <label
                            for="price"
                            >Price
                          </label>
                          {{form.price}}
                        </div>
                        <div class="form-group mb-3 col-xs-12 col-sm-6">
                          <label
                            for="mrp"
                            >MRP
                          </label>
                          {{form.mrp}}
                        </div>
                  </div>
                  <div class="form-group mb-3">
                    <label
                      for="description"
                      >Description</label
                    >
                    {{form.product_details}}
                  </div>
                  
              </div>
              
              <div class="col-xl-6 col-lg-6 col-md-12 mx-auto mb-4">
                <div class="custom-file mt-3 mb-3">
                  <label>Main Image</label>
                  {{form.main_img}}
                </div>
                <br><br>
                <label>Images</label>
                <div class="custom-file mt-3 mb-3">
                  {{form.img1}}                  
                </div>
                <div class="custom-file mt-3 mb-3">
                  {{form.img2}}                  
                </div>
                <div class="custom-file mt-3 mb-3">
                  {{form.img3}}                  
                </div>
              </div>

              <div class="col-12">
                <button type="submit" class="btn btn-primary btn-block text-uppercase">Add Product Now</button>
              </div>
            </form>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

templates/01-deals.html
{% extends '01-admin-base.html' %}
{% load static %}
{% block content %}

<div class="container mt-5">
      <h2 style="text-align: center; color: white;">DEALS <i class='fas fa-gift'></i></h2>
      <div class="row tm-content-row">
        <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 tm-block-col">
          <div class="tm-bg-primary-dark tm-block tm-block-products" >
            <div class="tm-product-table-container">
              <table class="table table-hover tm-table-small tm-product-table">
                <thead>
                  <tr>
                    <th scope="col">NAME</th>
                    <th scope="col">START DATE</th>
                    <th scope="col">END DATE</th>
                    <th scope="col">EDIT</th>
                  </tr>
                </thead>
                <tbody>

                  {% for deal in deals %}
                  <tr>
                    <td class="tm-product-name">{{deal.name}}</td>                    
                    <td>{{deal.start_date}}</td>
                    <td>{{deal.end_date}}</td>

                    <td>
                      <a href="/dashboard/edit-deal/{{deal.id}}" class="tm-product-delete-link tm-product-delete-icon">
                        <i class='fas fa-edit' ></i>
                      </a>
                    </td>
                  </tr>
                  {% endfor %}
                 
                </tbody>
              </table>
            </div>
            <a
              href="/dashboard/create-deals"
              class="btn btn-primary btn-block text-uppercase mb-3">Create New Deals</a>            
          </div>
        </div>
        
      </div>
    </div>
   
{% endblock content %}

   

templates/01-update-order.html
{% extends '01-admin-base.html' %}
{% load static %}
{% block content %}

<div class="container tm-mt-big tm-mb-big">
  <div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 mx-auto">
      <div class="tm-bg-primary-dark tm-block tm-block-h-auto">
        <div class="row">
          <div class="col-12">
            <h2 class="tm-block-title d-inline-block">Order Id: {{rep_order.order_id}}</h2>
          </div>
        </div>
        <div class="row tm-edit-product-row">
          <div class="col-xl-6 col-lg-6 col-md-12">
            <form action="/dashboard/update-order/{{rep_order.order_id}}" method="post" class="tm-edit-product-form">
              {% csrf_token %}
              <div class="form-group mb-3">
                <label
                  for="name"
                  >Customer Name
                </label>
                <input
                id="name"
                name="name"
                type="text"
                class="form-control validate"
                value="{{rep_order.cutomer_name.first_name}}"
                readonly style="background-color: #54657d;"
                />
              </div>
              <div class="form-group mb-3">
                <label
                for="address"
                >Address</label
                >
                <input
                  id="address"
                  name="address"
                  type="text"
                  class="form-control validate"
                  value="{{rep_order.address}}"
                  readonly style="background-color: #54657d;"
                />                
              </div>
              <div class="form-group mb-3">
                <label
                for="payment_method"
                >Payment Method</label
                >
                <input
                  id="payment_method"
                  name="payment_method"
                  type="text"
                  class="form-control validate"
                  value="{{rep_order.get_payment_method_display}}"
                  readonly style="background-color: #54657d;"
                />                
              </div>
              <div class="form-group mb-3">
                <label
                  for="order_status"
                  >Order Status</label
                >
                <select
                  class="custom-select tm-select-accounts"
                  id="order_status" name="order_status" style="color: white;"
                >
                  {% if rep_order.order_status == "pending" %}
                  <option value="pending" selected>Pending</option>
                  <option value="cancelled">Cancelled</option>
                  <option value="confirm">Confirm</option>
                  <option value="on_the_way">On the way</option>
                  <option value="delivered">Delivered</option>
                  
                  {% elif rep_order.order_status == "cancelled" %}
                  <option value="pending">Pending</option>
                  <option value="cancelled" selected>Cancelled</option>
                  <option value="confirm">Confirm</option>
                  <option value="on_the_way">On the way</option>
                  <option value="delivered">Delivered</option>

                  {% elif rep_order.order_status == "confirm" %}                    
                  <option value="pending">Pending</option>
                  <option value="cancelled">Cancelled</option>
                  <option value="confirm" selected>Confirm</option>
                  <option value="on_the_way">On the way</option>
                  <option value="delivered">Delivered</option>

                  {% elif rep_order.order_status == "on_the_way" %}                 
                  <option value="cancelled">Cancelled</option>
                  <option value="pending">Pending</option>
                  <option value="confirm">Confirm</option>
                  <option value="on_the_way" selected>On the way</option>
                  <option value="delivered">Delivered</option>
                  
                  {% elif rep_order.order_status == "delivered" %}
                  <option value="cancelled">Cancelled</option>
                  <option value="pending">Pending</option>
                  <option value="confirm">Confirm</option>
                  <option value="on_the_way">On the way</option>
                  <option value="delivered" selected>Delivered</option>
                  {% endif %}
                </select>
              </div>          
          </div>

          <div class="col-xl-6 col-lg-6 col-md-12 mx-auto mb-4">
            <div class="form-group mb-3">
              <label
                for="date"
                >Order Date
              </label>
              <input
                id="date"
                name="date"
                type="datetime"
                class="form-control validate"
                value="{{rep_order.date}}"
                readonly style="background-color: #54657d;"
              />
            </div>
            <div class="form-group mb-3">
              <label
                for="mobile_no"
                >Mobile Number
              </label>
              <input
                id="mobile_no"
                name="mobile_no"
                type="text"
                class="form-control validate"
                value="{{rep_order.mobile_no}}"
                readonly style="background-color: #54657d;"
              />
            </div>
            <div class="form-group mb-3">
              <label
                for="transaction_id"
                >Transaction Id
              </label>
              <input
                id="transaction_id"
                name="transaction_id"
                type="text"
                class="form-control validate"
                value="{{rep_order.transaction_id}}"
                readonly style="background-color: #54657d;"
              />
            </div>

            <div class="form-group mb-3">
              <label
                for="payment_status"
                >Payment Status</label
              >
              <select
                class="custom-select tm-select-accounts"
                id="payment_status" name="payment_status" style="color: white;"
              >
                {% if rep_order.payment_status == "pending" %}
                <option value="pending" selected>Pending</option>
                <option value="cancelled">Cancelled</option>
                <option value="confirm">Confirm</option>
                
                {% elif rep_order.payment_status == "cancelled" %}
                <option value="pending">Pending</option>
                <option value="cancelled" selected>Cancelled</option>
                <option value="confirm">Confirm</option>

                {% elif rep_order.payment_status == "confirm" %}                    
                <option value="pending">Pending</option>
                <option value="cancelled">Cancelled</option>
                <option value="confirm" selected>Confirm</option>

                {% endif %}
              </select>
            
            </div>
          </div>

          <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 tm-block-col">
            <div class="tm-bg-primary-dark tm-block tm-block-products" style="min-height: unset;">
              <div class="tm-product-table-container">
                <h3 style="text-align: center; color: white;">Product List</h3>
                <table class="table table-hover tm-table-small tm-product-table">
                  <thead>
                    <tr>
                      <th scope="col"></th>
                      <th scope="col">PRODUCT</th>
                      <th scope="col">QUANTITY</th>
                      <th scope="col">PRICE(₹)</th>
                      <th scope="col">TOTAL(₹)</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for item in orders %}
                    <tr>
                      <td >{{forloop.counter}}</td>
                      <td class="tm-product-name">{{item.product.name}}</td>
                      <td>{{item.quantity}}</td>
                      <td>{{item.price}}</td>
                      <td>{{item.total_cost}}</td>  
                    </tr>
                    {% endfor %}
                    <tr style="text-align: center;background: #3a4f60;
                    font-size: large;">
                      <td colspan="3">Grand Total</td>
                      <td colspan="2">₹ {{grand_total}}</td>
                    </tr>
                   
                  </tbody>
                </table>
              </div>
              <!-- table container -->
              
            </div>
          </div>
          <div class="col-12">
            <br><br>
            <button type="submit" class="btn btn-primary btn-block text-uppercase">Update Order
            </button>
            <br>
            <button type="button" class="btn btn-primary btn-block text-uppercase" onclick="javascript:window.open('/generate-report/{{rep_order.order_id}}', '_blank');" >Generate Report <i class="fas fa-file-pdf" aria-hidden="true"></i>
            </button>
          </div>

        </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/invoice_format.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
    
    <title>Invoice {{order_id}}</title>

    <style>
        .top_rw{ background-color:#f4f4f4; }
        .td_w{ }
        button{ padding:5px 10px; font-size:14px;}
        .invoice-box {
            max-width: 890px;
            margin: auto;
            padding:10px;
            border: 1px solid #eee;
            box-shadow: 0 0 10px rgba(0, 0, 0, .15);
            font-size: 14px;
            line-height: 24px;
            font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
            color: #555;
        }
        .invoice-box table {
            width: 100%;
            line-height: inherit;
            text-align: left;
            border-bottom: solid 1px #ccc;
        }
        .invoice-box table td {
            padding: 5px;
            vertical-align:middle;
        }
        .invoice-box table tr td:nth-child(2) {
            text-align: right;
        }
        .invoice-box table tr.top table td {
            padding-bottom: 20px;
        }
        .invoice-box table tr.top table td.title {
            font-size: 45px;
            line-height: 45px;
            color: #333;
        }
        .invoice-box table tr.information table td {
            padding-bottom: 10px;
        }
        .invoice-box table tr.heading td {
            background: #eee;
            border-bottom: 1px solid #ddd;
            font-weight: bold;
            font-size:12px;
        }
        .invoice-box table tr.details td {
            padding-bottom: 20px;
        }
        .invoice-box table tr.item td{
            border-bottom: 1px solid #eee;
        }
        .invoice-box table tr.item.last td {
            border-bottom: none;
        }
        .invoice-box table tr.total td:nth-child(2) {
            border-top: 2px solid #eee;
            font-weight: bold;
        }
        @media only screen and (max-width: 600px) {
            .invoice-box table tr.top table td {
                width: 100%;
                display: block;
                text-align: center;
            }
            .invoice-box table tr.information table td {
                width: 100%;
                display: block;
                text-align: center;
            }
        }
        /** RTL **/
        .rtl {
            direction: rtl;
            font-family: Tahoma, 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
        }
        .rtl table {
            text-align: right;
        }
        .rtl table tr td:nth-child(2) {
            text-align: left;
        }
    </style>

    
</head>

<body>

    <div class="invoice-box">
        <table cellpadding="0" cellspacing="0">
		<tr class="top_rw">
		   <td colspan="2">
		      <h2 style="margin-bottom: 0px;"> Invoice</h2>
              Order Date: {{rep_order.date}} 
		   </td>
		    <td  style="width:40%; margin-right: 10px;">
                <h1 style="margin-bottom: 0px;">{{rep_order.get_payment_method_display}}</h1>
		        Order Id: <b>{{order_id}}</b>
		   </td>
		</tr>
            <tr class="information">
                  <td colspan="3">
                    <table>
                        <tr>
                            <td colspan="2">
							<b> Shipping Address: {{rep_order.cutomer_name.first_name}} </b> <br>
                                {{rep_order.address}}<br>
                                Mo.No. {{rep_order.mobile_no}}<br>
                                {{rep_order.cutomer_name.email}}<br>
                            </td>
                            <td> <b> Billing Address: {{user.first_name}} </b><br>
                                {{user.extended_user.address}}<br>
                                Mo.No. {{user.extended_user.mobile_no}}<br>
                                {{user.email}}
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
                            <td colspan="3">
            <table cellspacing="0px" cellpadding="2px">
            <tr class="heading">
                <td style="width:50%;">
                    ITEM
                </td>
				<td style="width:15%; text-align:center;">
                    QTY.
                </td>
                <td style="width:15%; text-align:right;">
                    PRICE (INR)
                </td>
				
				 <td style="width:20%; text-align:right;">
                   TOTAL AMOUNT (INR)
                </td>
            </tr>
            {% for order in orders %}
			<tr class="item">
               <td style="width:50%;">
                    {{order.product}}
                </td>
				<td style="width:15%; text-align:center;">
                    {{order.quantity}}
                </td>
                <td style="width:15%; text-align:right;">
                    {{order.price}}
                </td>
				 <td style="width:20%; text-align:right;">
                    {{order.total_cost}}
                </td>
            </tr>
            {% endfor %}
			
			</table>
            <tr class="total">
                  <td colspan="3" align="right">  Grand Total : <b> {{grand_total}} </b> Rupees </td>
            </tr>
			<tr>
			   <td colspan="3">
			     <table cellspacing="0px" cellpadding="2px">
				    <tr>
			            <td width="50%">
						<b> Thank You! </b> <br>
                            Visit Again
						</td>
						<td>
						 * This is a computer generated invoice and does not
						  require a physical signature
						</td>
			        </tr>
					 <tr>
			            <td width="50%">
						</td>
						<td>
						 	<b> Authorized Signature </b>
							<br>
							<br>
							...................................
							<br>
							<br>
							<br>
						</td>
			        </tr>
			     </table>
			   </td>
			</tr>
        </table>
    </div>


</body>
</html>

templates/order_history.html
{% extends 'base.html' %}
{% load static %}
{% block content %}




	<!-- banner-2 -->
	<div class="page-head_agile_info_w3l">

	</div>
	<!-- //banner-2 -->
	<!-- page -->
	<div class="services-breadcrumb">
		<div class="agile_inner_breadcrumb">
			<div class="container">
				<ul class="w3_short">
					<li>
						<a href="index.html">Home</a>
						<i>|</i>
					</li>
					<li>Order History</li>
				</ul>
			</div>
		</div>
	</div>
	<!-- //page -->
	<!-- FAQ-help-page -->
	<div class="faqs-w3l">
		<div class="container">
			<!-- tittle heading -->
			<h3 class="tittle-w3l">Order History
				<span class="heading-style">
					<i></i>
					<i></i>
					<i></i>
				</span>
			</h3>
			<!-- //tittle heading -->
			
			<div class="faq-w3agile">
				<br>
				<table class="timetable_sub">
					<thead>
						<tr>
							<th>Order Id</th>
							<th>Date</th>
							<th>Order Status</th>
							<th>Payment Status</th>
							<th>Payment Mode</th>
							<th>Transaction Id</th>
						</tr>
					</thead>

					<tbody>
						{% regroup orders by order_id as order_ids %}

						{% for order in order_ids %}
						<tr class="rem{{forloop.counter}}">
							
							{% for record in order.list %}
							{% if forloop.counter == 1 %}

							<td class="invert">
								<a href="/checkout/{{order.grouper}}">
									{{order.grouper}}
								</a>
							</td>
							<td class="invert">{{record.date}}</td>
							<td class="invert">{{record.get_order_status_display}}</td>
							<td class="invert">{{record.get_payment_status_display}}</td>
							<td class="invert">{{record.get_payment_method_display}}</td>
							<td class="invert">{{record.transaction_id}}</td>

							{% endif %}
							{% endfor %}

							<input type="hidden" id="product_id" name="product{{forloop.counter}}" value="{{product.id}}">
							
						</tr>
						{% endfor %}
					</tbody>
					
				</table>

			</div>
		</div>
	</div>
	<!-- //FAQ-help-page -->
{% endblock %}